### ISSUE TITLE
Boost DSO missing from command line

### ISSUE THREAD

**Issue by Ender97** [jackz314/bars-to-bwav#2]
On Ubuntu 18.04, using make to build results in this error: 

`/usr/bin/ld: /tmp/ccJDb16N.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:4: recipe for target 'compile' failed
make: *** [compile] Error 1
`

I really don't understand code, and it took me over an hour of searching and head scratching, but I managed to fix it. I was able to solve the problem by altering the make file to include `-lboost_system`

It seems to be a simple solution, and I think the issue has to do with using a newer version of Boost. I'll attach the altered makefile that worked with my system. 

Also, _thank you so much for making this!_ It's an invaluable tool for unpacking these kinds of files. I love Ubuntu, but I think this would have way more exposure if it could also run in Windows. I tried to compile the .cpp file into an .exe using g++ but sadly I don't really know what I'm doing. I couldn't get it to run in a Windows terminal. 

[Makefile.txt](https://github.com/jackz314/bars-to-bwav/files/4788456/Makefile.txt)

(I had two problems come up, but I'm going to put them into different tickets.)

**Comment by jackz314** [comment]
This does seem to be a problem with Boost not being able to find the right library files, I've updated the Makefile to reflect that, thanks for this!
